### ISSUE TITLE
test_sample_data_1.txt not exists

### ISSUE THREAD

**Issue by swuecho** [ArnaoutLab/Recon#2]
with a newline character delimiting lines. Species size is an integer. Sample data in this format can be found in the file test_sample_data_4.txt; in it, species 9_0 has a size of 9 individuals, individual, species 8_0 has 8 individuals, species 1_1833458 has 1 individual, etc.

Note that files in this format can be long and therefore take a few seconds to read (test_sample_data_4.txt is over two million lines long). The alternative species distribution format (-c below) is much more compact and therefore faster to read. For example, test_sample_data_1.txt contains the same information as test_sample_data_4.txt, only in this more compact format, and runs in ~2 seconds vs. ~7 seconds for test_sample_data_4.txt.

**Comment by rarnaout** [comment]
@swuecho you appear to be referencing the manual; if so, the filenames should have been test_sample_1.txt etc., without "_data" in them. I've updated the manual accordingly. The actual files you want are in the repository, as far as I can tell
